# Generated by Django 2.2.24 on 2021-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general_enquiry', 'General Enerquy'), ('request_a_call_back', 'Request A Call Back'), ('customer_service_enquiry', 'Customer Service Enquiry')], max_length=100)),
                ('name', models.CharField(default='', max_length=64)),
                ('content', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(default='', max_length=64)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
