# Generated by Django 2.2.24 on 2021-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General Enquiry', 'General Enerquy'), ('Request A Call Back', 'Request A Call Back'), ('Customer Service Enquiry', 'Customer Service Enquiry')], max_length=100)),
            ],
        ),
    ]
