# Generated by Django 2.2.24 on 2021-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollected',
            name='location',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='datacollected',
            name='name',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
