# Generated by Django 2.2.24 on 2021-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollected',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
