# Generated by Django 2.2.24 on 2021-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_auto_20210819_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollected',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datacollected',
            name='type',
            field=models.CharField(choices=[('general_enquiry', 'General Enerquy'), ('request_a_call_back', 'Request A Call Back'), ('customer_service_enquiry', 'Customer Service Enquiry')], max_length=100),
        ),
    ]
