# Generated by Django 2.2.24 on 2021-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0003_auto_20210820_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollected',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='datacollected',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='datacollected',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='datacollected',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
