# Generated by Django 2.2.24 on 2021-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0004_auto_20210824_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollected',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
